version: "3.8"

services:
  api:
    build: .
    command: node dist/server.js
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
      - localstack
    networks:
      - local-dev

  worker:
    build: .
    command: node dist/worker.js
    env_file:
      - .env
    depends_on:
      - db
      - localstack
    networks:
      - local-dev

  recovery:
    build: .
    command: node dist/recovery.js
    env_file:
      - .env
    depends_on:
      - db
      - localstack
    networks:
      - local-dev

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - local-dev

  localstack:
    image: localstack/localstack:3.0
    container_name: localstack
    ports:
      - "4566:4566"                # LocalStack gateway
    environment:
      - SERVICES=s3,sqs,sns,dynamodb
      - DEBUG=1
      - AWS_DEFAULT_REGION=ap-south-1
    volumes:
      - localstack-data:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - local-dev

volumes:
  pgdata:
  localstack-data:

networks:
  local-dev:
    driver: bridge